Select  *  into mah_full_suppli From [MH_SUP_New2].[dbo].[AC_001] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_002] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_003] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_004] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_005] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_006] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_007] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_008] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_009] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_010] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_011] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_012] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_013] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_014] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_015] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_016] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_017] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_018] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_019] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_020] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_021] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_022] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_023] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_024] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_025] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_026] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_027] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_028] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_029] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_030] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_031] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_032] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_033] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_034] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_035] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_036] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_037] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_038] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_039] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_040] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_041] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_042] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_043] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_044] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_045] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_046] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_047] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_048] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_049] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_050] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_051] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_052] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_053] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_054] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_055] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_056] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_057] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_058] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_059] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_060] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_061] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_062] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_063] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_064] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_065] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_066] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_067] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_068] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_069] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_070] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_071] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_072] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_073] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_074] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_075] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_076] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_077] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_078] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_079] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_080] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_081] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_082] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_083] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_084] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_085] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_086] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_087] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_088] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_089] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_090] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_091] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_092] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_093] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_094] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_095] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_096] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_097] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_098] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_099] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_100] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_101] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_102] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_103] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_104] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_105] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_106] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_107] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_108] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_109] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_110] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_111] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_112] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_113] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_114] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_115] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_116] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_117] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_118] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_119] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_120] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_121] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_122] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_123] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_124] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_125] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_126] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_127] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_128] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_129] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_130] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_131] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_132] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_133] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_134] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_135] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_136] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_137] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_138] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_139] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_140] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_141] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_142] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_143] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_144] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_145] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_146] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_147] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_148] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_149] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_150] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_151] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_152] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_153] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_154] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_155] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_156] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_157] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_158] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_159] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_160] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_161] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_162] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_163] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_164] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_165] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_166] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_167] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_168] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_169] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_170] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_171] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_172] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_173] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_174] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_175] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_176] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_177] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_178] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_179] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_180] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_181] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_182] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_183] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_184] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_185] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_186] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_187] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_188] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_189] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_190] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_191] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_192] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_193] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_194] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_195] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_196] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_197] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_198] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_199] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_200] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_201] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_202] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_203] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_204] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_205] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_206] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_207] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_208] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_209] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_210] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_211] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_212] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_213] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_214] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_215] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_216] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_217] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_218] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_219] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_220] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_221] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_222] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_223] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_224] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_225] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_226] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_227] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_228] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_229] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_230] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_231] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_232] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_233] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_234] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_235] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_236] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_237] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_238] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_239] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_240] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_241] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_242] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_243] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_244] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_245] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_246] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_247] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_248] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_249] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_250] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_251] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_252] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_253] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_254] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_255] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_256] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_257] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_258] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_259] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_260] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_261] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_262] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_263] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_264] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_265] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_266] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_267] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_268] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_269] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_270] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_271] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_272] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_273] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_274] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_275] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_276] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_277] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_278] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_279] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_280] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_281] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_282] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_283] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_284] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_285] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_286] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_287] UNION ALL
Select  *  From [MH_SUP_New2].[dbo].[AC_288] ;

